name: pr
on:
  pull_request:
  workflow_dispatch:
jobs:
  check-pr:
    name: Check PR
    runs-on: ubuntu-latest
    steps:
      # Checkout your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Install zshell
        run: sudo apt install -y zsh
      - shell: bash
        run: |
          curl -sfL 'https://raw.githubusercontent.com/orcasecurity/orca-cli/main/install.sh' | bash -s
          orca-cli -h
          rm -rf /usr/local/bin/orca-cli
      - shell: sh
        run: |
          curl -sfL 'https://raw.githubusercontent.com/orcasecurity/orca-cli/main/install.sh' | bash -s
          orca-cli -h
          rm -rf /usr/local/bin/orca-cli
      - shell: zsh {0}
        run: |
          curl -sfL 'https://raw.githubusercontent.com/orcasecurity/orca-cli/main/install.sh' | bash -s
          orca-cli -h
          rm -rf /usr/local/bin/orca-cli
      
