name: pr
on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  check-pr:
    name: Check PR
    runs-on: ubuntu-latest
    steps:
      # Checkout your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Repository
        uses: actions/checkout@v3

      - shell: bash
        run: |
          curl -sfL 'https://raw.githubusercontent.com/orcasecurity/orca-cli/main/install.sh' | bash -s
          orca-cli -p default --api-token ${{ secrets.ORCA_SECURITY_API_TOKEN }} secrets scan --path . --disable-git-scan
