name: pr
on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  secret_check:
    name: secret_check
    runs-on: ubuntu-latest
    steps:
      # Checkout your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - shell: bash
        run: |
          curl -sfL 'https://raw.githubusercontent.com/orcasecurity/orca-cli/main/install.sh' | bash -s
          orca-cli -p default --api-token ${{ secrets.ORCA_SECURITY_API_TOKEN }} secrets scan --path .  --from-commit 03f6689796b4c982812be8b40ba53811830bb164
