name: pr
on:
  pull_request:
  workflow_dispatch:
jobs:
  check-pr:
    name: Check PR
    runs-on: ubuntu-latest
    steps:
      # Checkout your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Repository
        uses: actions/checkout@v3

      - shell: bash
        run: |
          expr 1 + 1 > output.log
